export const ADD_FOLLOWER = 'ADD_FOLLOWER';
export const REDUCE_FOLLOWER = 'REDUCE_FOLLOWER';
export const SET_FOLLOWED = 'SET_FOLLOWED';
export const RESET_FOLLOWER = 'RESET_FOLLOWER';
export const ADD_ONLINE_PEOPLE = 'ADD_ONLINE_PEOPLE';
export const REDUCE_ONLINE_PEOPLE = 'REDUCE_ONLINE_PEOPLE';
